version: "3.9"
services:
   appgateway:
      build: ./Gateway
      restart: always
      ports:
       - "8000:8000"
   FactoryApp:
      build:
         context: ./FactoryApp
      restart: always
      links:
       - redis
       - appgateway
      ports:
       - "5000"
   worker:
      image: jaredv/rq-docker:0.0.2
      command: rq worker -u redis://redis:6379 high normal low
      deploy:
         replicas: 4
      depends_on:
       - master
      links:
       - redis
       - FactoryApp
   redis:
      image: redis
      ports:
       - "6379:6379"
      volumes:
       - ./redis:/data
   rq-dashboard:
      image: jaredv/rq-docker:0.0.2
      command: rq-dashboard -H rq-server
      ports:
       - "9181:9181"
